# Java
java_version=21

# Loader
obfuscated_minecraft=true
minecraft_version=1.20.6
compatible_minecraft_versions=["1.20.5", "1.20.6"]
fabric_loader_version=0.17.0
access_widener_version=1_20_6
mc_publish_dependencies_list=["placeholder-api@2.4.0-pre.2+1.20.5(embedded)"]

# Mod dependencies
carpet_core_version=1.20.6-1.4.141+v240429
sgui_version=1.5.1+1.20.5
placeholder_api_version=2.4.0-pre.2+1.20.5
luckperms_api_version=5.4
common_economy_api_version=1.1.1
