# Java
java_version=17

# Loader
minecraft_version=1.20.1
compatible_minecraft_versions=["1.20", "1.20.1"]
fabric_loader_version=0.17.0
yarn_mappings_version=1.20.1+build.10
access_widener_version=1_20_1
mc_publish_dependencies_list=["placeholder-api@2.1.4+1.20.1(embedded)"]

# Mod dependencies
carpet_core_version=1.20-1.4.112+v230608
sgui_version=1.2.2+1.20
placeholder_api_version=2.1.4+1.20.1
luckperms_api_version=5.4
common_economy_api_version=1.1.1
