# Java
java_version=21

# Loader
minecraft_version=1.21.1
compatible_minecraft_versions=["1.21", "1.21.1"]
fabric_loader_version=0.17.0
yarn_mappings_version=1.21.1+build.3
access_widener_version=1_21
mc_publish_dependencies_list=["placeholder-api@2.4.1+1.21(embedded)"]

# Mod dependencies
carpet_core_version=1.21-1.4.147+v240613
sgui_version=1.6.0+1.21
placeholder_api_version=2.4.1+1.21
luckperms_api_version=5.4
common_economy_api_version=1.1.1
