# Java
java_version=21

# Loader
obfuscated_minecraft=true
minecraft_version=1.21.11
compatible_minecraft_versions=["1.21.11"]
fabric_loader_version=0.17.0
access_widener_version=1_21_11
mc_publish_dependencies_list=["placeholder-api@2.8.0+1.21.9 (embedded)"]

# Mod dependencies
carpet_core_version=1.21.11-1.4.193+v251211
sgui_version=1.11.0+1.21.9
placeholder_api_version=2.8.0+1.21.9
luckperms_api_version=5.4
common_economy_api_version=1.1.1
