# Java
java_version=25

# Loader
obfuscated_minecraft=false
minecraft_version=26.3
compatible_minecraft_versions=["26.3"]
fabric_loader_version=0.19.5
access_widener_version=26_3
mc_publish_dependencies_list=["placeholder-api@3.2.0+26.3 (embedded)"]

# Mod dependencies
sgui_version=2.2.0+26.3
placeholder_api_version=3.2.0+26.3
luckperms_api_version=5.5
common_economy_api_version=2.0.0
