# Define the crowdin tokens.
project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_TOKEN

# Path to your project directory, relative to the `crowdin.yml` file.
base_path: .

# Saving the same file system structure on crowdin server.
preserve_hierarchy: true

# Define the location to push-to-crowdin and pull-from-crowdin. (Relative to the base_path variable)
files: [
  {
    "source": "push-to-crowdin/en_US.json",
    "translation": "pull-from-crowdin/%locale_with_underscore%.json"
  }
]