# Loader
minecraft_version=1.21.4
fabric_loader_version=0.16.9
yarn_mappings_version=1.21.4+build.1
access_widener_version=1_21_4

# Mod dependencies
carpet_core_version=1.21.4-1.4.161+v241203
sgui_version=1.8.1+1.21.4
placeholder_api_version=2.5.1+1.21.3
luckperms_api_version=5.4